VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	config.vm.define "docker-repo", autostart: false do |instance|
		instance.vm.hostname = "docker-host"
		instance.vm.box = "queenbee/debian-docker"
		instance.vm.box_url = "file://../image/debian-docker/debian-8.0.0-amd64_virtualbox.box"
		instance.vm.network "forwarded_port", guest: 4243, host: 4243
		instance.vm.network "forwarded_port", guest: 8080, host: 8080
		instance.vm.provision "shell", path: "docker-repo/provision.sh"
	end
end

