#!/usr/bin/ruby -w
#
# This file is part of QueenBee Project.
#
# QueenBee Project is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# QueenBee Project is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with QueenBee Project.  If not, see <http://www.gnu.org/licenses/>.
#

VAGRANTFILE_API_VERSION = "2"

IMAGE_BASE_URL = "file://../image"
DDNS_IP = "192.168.53.2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

	config.vm.provision "shell" do |s|
		s.path = "setup.sh"
		s.args = [DDNS_IP]
	end
	config.vm.synced_folder "vagrant", "/vagrant", create: true
	
	config.vm.define "ddns", autostart: true do |instance|
		instance.vm.hostname = "ddns"
		instance.vm.box = "queenbee/debian-ddns"
		instance.vm.box_url = "#{IMAGE_BASE_URL}/debian/debian-8.1.0-amd64-ddns_virtualbox.box"
		instance.vm.network "private_network", ip: DDNS_IP
		instance.vm.provision "shell", path: "ddns/setup.sh"
	end
	
	config.vm.define "docker", autostart: true do |instance|
		instance.vm.hostname = "docker"
		instance.vm.box = "queenbee/debian-docker"
		instance.vm.box_url = "#{IMAGE_BASE_URL}/debian/debian-8.1.0-amd64-docker_virtualbox.box"
		instance.vm.network "private_network", type: "dhcp"
		instance.vm.provision "shell", path: "docker/setup.sh"
	end
	
end

