---

- hosts: localhost
  tasks:
  
  - name: Build 'caappserv' image
    docker_image:
      docker_url: http://localhost:4243
      path: image/docker-caappserv
      name: queenbee/caappserv
      state: build

  - name: Run 'caappserv' image
    docker:
      docker_url: http://localhost:4243
      image: queenbee/caappserv
      ports:
      - "8080:8080"
      state: started
